package com.example.demo.service;

import com.example.demo.dto.BulkWaybillResult;
import com.example.demo.model.WaybillRecord;
import com.example.demo.repository.WaybillFileRepository;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import com.example.demo.dto.FailureRow;
import org.springframework.web.client.HttpStatusCodeException;
import com.fasterxml.jackson.databind.ObjectMapper;


import java.util.List;
import java.util.Map;
import java.util.ArrayList;

@Service
public class BluedartWaybillService {

    private final BluedartAuthService authService;
    private final WaybillFileRepository repository;
    private final RestTemplate restTemplate = new RestTemplate();

    public BluedartWaybillService(
            BluedartAuthService authService,
            WaybillFileRepository repository
    ) {
        this.authService = authService;
        this.repository = repository;
    }

    @SuppressWarnings("unchecked")
public Map<String, Object> generateWaybill(Map<String, Object> requestBody) {
String jwtToken;

try {
    jwtToken = authService.getJwtToken();
    System.out.println("JWT = " + jwtToken);
} catch (Exception e) {
    System.err.println("JWT TOKEN ERROR");
    e.printStackTrace();
    throw e;
}


    HttpHeaders headers = new HttpHeaders();
    headers.set("JWTToken", jwtToken);
    headers.setContentType(MediaType.APPLICATION_JSON);

    HttpEntity<Map<String, Object>> entity =
            new HttpEntity<>(requestBody, headers);

    Map<String, Object> responseBody;

    try {
        System.out.println("➡️ Sending request to Bluedart:");
        System.out.println(requestBody);

        ResponseEntity<Map> response = restTemplate.postForEntity(
                "https://apigateway-sandbox.bluedart.com/in/transportation/waybill/v1/GenerateWayBill",
                entity,
                Map.class
        );

        responseBody = response.getBody();

        if (responseBody == null) {
            throw new RuntimeException("Empty response from Bluedart");
        }

    // } catch (Exception e) {
    //     System.err.println("❌ Bluedart API FAILED");
    //     System.err.println("➡️ Payload that caused failure:");
    //     System.err.println(requestBody);
    //     e.printStackTrace();
    //     throw new RuntimeException("Bluedart API error", e);
    // }
    } catch (HttpStatusCodeException ex) {

    String errorBody = ex.getResponseBodyAsString();

    System.err.println("❌ Bluedart API FAILED");
    System.err.println("➡️ Bluedart error response:");
    System.err.println(errorBody);

    String message = extractBluedartErrorMessage(errorBody);

    throw new RuntimeException(message);

} catch (Exception e) {
    throw new RuntimeException("Unexpected error while calling Bluedart", e);
}



    /* ---------- VALIDATE RESPONSE ---------- */

    Map<String, Object> result =
            (Map<String, Object>) responseBody.get("GenerateWayBillResult");

    if (result == null || result.get("AWBNo") == null) {
        throw new RuntimeException(
                "Waybill not generated by Bluedart. Response: " + responseBody
        );
    }

    String awbNo = result.get("AWBNo").toString();

    /* ---------- PERSIST WAYBILL ---------- */

    try {
        repository.save(
                new WaybillRecord(
                        awbNo,
                        extractCreditRef(requestBody),
                        requestBody,
                        responseBody
                )
        );
    } catch (Exception e) {
        // Persistence failure should NOT hide Bluedart success
        System.err.println("⚠️ Failed to save WaybillRecord for AWB: " + awbNo);
        e.printStackTrace();
    }

    return responseBody;
}


    private String extractCreditRef(Map<String, Object> requestBody) {
        try {
            Map<String, Object> req =
                    (Map<String, Object>) requestBody.get("Request");
            Map<String, Object> services =
                    (Map<String, Object>) req.get("Services");
            return services.getOrDefault("CreditReferenceNo", "NA").toString();
        } catch (Exception e) {
            return "NA";
        }
    }

    public BulkWaybillResult generateBulkWaybills(List<Map<String,Object>> requests) {

        BulkWaybillResult result=new BulkWaybillResult();
        result.setTotal(requests.size());


        //List<WaybillRecord> successRecords=new ArrayList<>();

        int rowNo=1;

        for(Map<String,Object> request:requests){

            try {
                Map<String,Object> response = generateWaybill(request);

                Map<String,Object> gwb=
                        (Map<String,Object>) response.get("GenerateWayBillResult");

                String awbNo = gwb.get("AWBNo").toString();

                WaybillRecord record = repository.findByAwbNo(awbNo);

                if(record!=null) {
                    //successRecords.add(record);
                    result.getSuccessRecords().add(record);
                }

            } catch (Exception e) {
               String ref=extractCreditRef(request);
               result.getFailures().add(
                   new FailureRow(rowNo, ref, e.getMessage())
               );
            }
            rowNo++;
        }
        result.setSuccess(result.getSuccessRecords().size());
        result.setFailed(result.getFailures().size());  
        // repository.saveAll(successRecords);
        return result;
    }

    @SuppressWarnings("unchecked")
private String extractBluedartErrorMessage(String responseBody) {

    try {
        ObjectMapper mapper = new ObjectMapper();
        Map<String, Object> root = mapper.readValue(responseBody, Map.class);

        Object errObj = root.get("error-response");

        if (errObj instanceof List<?> errors && !errors.isEmpty()) {

            Object first = errors.get(0);

            if (first instanceof Map<?, ?> errMap) {

                Object statusObj = errMap.get("Status");

                if (statusObj instanceof List<?> statuses && !statuses.isEmpty()) {

                    Object st = statuses.get(0);

                    if (st instanceof Map<?, ?> statusMap) {

                        Object info = statusMap.get("StatusInformation");

                        if (info != null) {
                            return info.toString();
                        }
                    }
                }
            }
        }
    } catch (Exception ignored) {}

    return "Bluedart rejected the request";
}


}
